config/routes.rb
Dayspace::Application.routes.draw do

  get "about" => "contents#about"

  get "team" => "contents#team"

  
  get "request_invite" => "users#edit"
  
  resources :users

  root :to => "landing#index"

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
	
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def about
  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

	def index	
		@user_count = User.count
		@user = User.new
		
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	
	# def new
	# 	@user = User.new	
	# end

	def create
		p "******** now in our create users controller!!!!!!!!! " * 10
		@user = User.create(user_params)
		@user.save
		p params
		redirect_to request_invite_path
	end

	def edit
		p "**** WE'RE IN EDIT!!!!!!!!!!!!!!!!!!!!!" * 15
		user = User.find_by_email(params[:email])
		session[:user_id] = user.id
		p params
	end

	def index
		
	end

	def show

	end

	private

		def user_params
			params.require(:user).permit!
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/about.html.erb
<!-- <div class = "background">
	<img src="assets/landing-bg-2.jpg" class="img-responsive" alt="Responsive image" id="background">
 -->

<div class="row">
	<div class = "col-md-6 col-md-offset-3">
		<div class = "content_space text_padding">
			<h2> One Man's Dining room is another Woman's corporate headquarters. </h2>
			<p> DaySpace.co allows you to rent out your home during the day, or find space to work besides your typical office or coffee shop. Most homes are empty for 1/3 of the day, so DaySpace has made it goal to allow this space to be utilized. Join the sharing economy by joining DaySpace.co today!</p> 
		</div>
		

		<h3>Team</h3>

		<div class = "team">

			<div class="row">
				<div class = "bio col-md-4">
					<img src="assets/bitmaker_me-400-400.jpg" class="img-responsive">
					<div class = "bio-info">
						@drew_sing
						www.drewsing.com
					</div>	
				</div>
			
				<div class = "bio col-md-4">
					<img src="assets/annie_sing_400_400.jpg" class="img-responsive">
					<span>Annie Sing</span>
				</div>	

				<div class = "bio col-md-4">
					<img src="assets/eric.jpg" class="img-responsive">
					<span>Eric DeBusschere</span>
				</div>	

			</div>
		</div>

		</div>
	</div>
</div>















<!-- <div class = "bg-overlay">
	<div id = "grind">
		<div class = "row">
			<div id = "box-2" class = "col-md-4 col-md-offset-4 black-trans">			
				<div class = "row">
					<div class = "col-md-8 col-md-offset-2">

						<h4>Thanks! We've added you to the list and will be releasing our MVP shortly.</h1>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>
 -->

app/views/landing/index.html.erb
<div class = "background">
	<img src="assets/landing-bg-1.jpg" class="img-responsive" alt="Responsive image" id="background">
</div>

	<div class = "bg-overlay">
		<div class = "row">
			<div id = "box-1" div class = "col-md-6 col-md-offset-2 white-trans">	
				<h2>My home is your workspace </h2>
					<h4 class= "gray-text">Join the sharing economy by renting out your home during the day.</h4>
			</div>
		</div>

			<%= form_for @user, url: users_path, method: 'post' do |f| %>	
				<div class = "row">
					<div id = "box-2" class = "col-md-4 col-md-offset-4 black-trans">			
						<div class = "row">
							<div class = "col-md-8 col-md-offset-2">
								<h4>I'd like to:</h4>
								<label class = "checkbox">
									<%= f.check_box :provide %>
									<%= f.label "Provide my space" %>
			    			</label>	
			    			<label class = "checkbox">
									<%= f.check_box :rent %>
			    				<%= f.label "Rent space" %>
			    			</label>					
							</div>
						</div>
			 
				<div class = "row">
					<div class = "col-md-8 col-md-offset-2" id = "email-field">

						<%= f.text_field :email, placeholder: "email", class: "form-control" %>

					</div>
				</div>

					<%= submit_tag "Request Invite", class: "btn btn-lg btn-default hero-button" %>
					<br>
					<div id= "counter" class = "center">
						<%= @user_count + 109 %> people have requested an invite</p>
					</div>
	

		<% end %>	
				</div>
			</div>
		</form>
	</div>
	

app/views/landing/request_invite.html.erb
<div class = "background">
	<img src="assets/landing-bg-2.jpg" class="img-responsive" alt="Responsive image" id="background">
</div>

<div class = "bg-overlay">
	<div id = "grind">
		<%= form_for User.new do |f| %>

			<div class = "row">
				<div id = "box-request-invite" class = "col-md-4 col-md-offset-4">		
					<ul id="section-tabs">
			      <li class="current active"><span>1.</span> You</li>
			      <li><span>2.</span> Location</li>
			      
			    </ul>	
					<div class = "row">
						<div class = "col-md-8 col-md-offset-2">

							<%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>

							<%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
							<br>
							<br>
							<%= f.text_field :city, placeholder: "City", class: "form-control" %>

							<%= f.text_field :neighborhood, placeholder: "Neighborhood", class: "form-control" %>	

							<%= f.text_field :phone, placeholder: "Mobile Number", class: "form-control" %>			
							<br>	

						</div>
					</div>
		 
		 		<a href="#" id="play">Paint it red</a>
				<%= submit_tag "Submit", class: "btn btn-lg btn-primary hero-button" %>
				
		<% end %>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/"><img src= "assets/dayspace_logo_136_28.gif"></a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    
    <ul class="nav navbar-nav">
      <li><a href="#"></a></li>
      <li><a href="#"></a></li>   
    </ul>
   

    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "About DaySpace", about_path %></li>
      <li><a href="#"></a></li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dayspace</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<%= render "layouts/header" %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<div class = "background">
	<img src="assets/landing-bg-2.jpg" class="img-responsive" alt="Responsive image" id="background">
</div>

<div class = "bg-overlay">
	<div id = "grind">
		

		<%= form_for User.new do |f| %>

			<div class = "row">
				<div id = "box-request-invite" class = "col-md-4 col-md-offset-4">		
					<ul id="section-tabs">
			      <li class="current active"><span>1.</span> You</li>
			      <li><span>2.</span> Location</li>
			      
			    </ul>	
					<div class = "user-form-1 row">
						<div class = "col-md-8 col-md-offset-2">

							<%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
							<%= f.text_field :last_name, placeholder: "Last Name", class: "form-control clever-text" %>
							<div id = "display">
							</div>
							<%= f.text_field :city, placeholder: "City", class: "form-control margin-top-forty" %>
							<%= f.text_field :neighborhood, placeholder: "Neighborhood", class: "form-control" %>	
							<%= f.text_field :phone, placeholder: "Mobile Number", class: "form-control" %>			
								

						</div>
					</div>
		 
		 		<a href="#" id="play">Paint it red</a>
				<%= submit_tag "Submit", class: "btn btn-lg btn-primary hero-button" %>
				
		<% end %>
	</div>
</div>